version: '3.9'

services:
   
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
    volumes:
      - dataBase:/var/lib/mysql
    ports:
      - 80:80


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:8000 
  